apiVersion: v1
kind: Service
metadata:
  name: statstream-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # For GCP Load Balancer
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: statstream
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statstream-app
  labels:
    app: statstream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statstream
  template:
    metadata:
      labels:
        app: statstream
    spec:
      containers:
      - name: statstream-app
        image: europe-north1-docker.pkg.dev/innate-might-447809-r8/statstream-repo/statstream:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: laravel
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: app-key
        - name: APP_ENV
          value: production
        - name: APP_DEBUG
          value: "false"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
