steps:
# Build the main application image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/statstream:$SHORT_SHA', '.']

# Build the scraper image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/scraper:$SHORT_SHA', '-f', 'docker/scrapers/Dockerfile', '.']

# Push the images
images:
- 'gcr.io/$PROJECT_ID/statstream:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/scraper:$SHORT_SHA'
