steps:
# Build the main application image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'europe-north1-docker.pkg.dev/$PROJECT_ID/statstream-repo/statstream:latest'
    - '.'

# Build the scraper image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'europe-north1-docker.pkg.dev/$PROJECT_ID/statstream-repo/scraper:latest'
    - '-f'
    - 'docker/scrapers/Dockerfile'
    - '.'

# Push the images
images:
- 'europe-north1-docker.pkg.dev/$PROJECT_ID/statstream-repo/statstream:latest'
- 'europe-north1-docker.pkg.dev/$PROJECT_ID/statstream-repo/scraper:latest'
