steps:
# Build the main application image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/statstream:latest'
    - '.'

# Build the scraper image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/scraper:latest'
    - '-f'
    - 'docker/scrapers/Dockerfile'
    - '.'

# Push the images
images:
- 'gcr.io/$PROJECT_ID/statstream:latest'
- 'gcr.io/$PROJECT_ID/scraper:latest'
